use_frameworks!

target 'RxSwiftExpansion_Example' do
  pod 'RxSwiftExpansion', :path => '../'
  pod 'SwiftExpansion', :path => '../../SwiftExpansion'

  target 'RxSwiftExpansion_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2'
    pod 'Nimble', '~> 7.0'
  end
end
